### ISSUE TITLE
Package order in default.nix

### ISSUE THREAD

**Issue by adfaure** [oar-team/kapack#16]
How should we organize the order of the packages in `default.nix`.
If an order is already defined, maybe we could write it down somewhere, to help developers and increase consistency ?

**Comment by freuk** [comment]
AFAIK there is no simple solution to that, and namespacing is too verbose and harder to
maintain.. 

Quoting Adrien FAURE (2018-12-07 08:59:24)

**Comment by mickours** [comment]
I propose to be messy and to close this one.
