### ISSUE TITLE
[doc] Force cloning?

### ISSUE THREAD

**Issue by mpoquet** [oar-team/kapack#7]
The current (fe34284) README tells to clone the kapack repository before anything else.

Would not it be better for users to use an URL to kapack's master tarball instead of cloning the repo? Or maybe just write the different options for users.

**Comment by freuk** [comment]
Can users add kapack as a channel directly using the github master URL?
Without a binary cache?

Quoting Michael Mercier (2018-10-22 11:26:27)
> I agree, PR welcomed ;)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

Valentin

**Comment by freuk** [comment]
one way is `nix-env -f <tarball-url> -iA <attribute name>`.
